<?php
return [
    "accepted_code_type" => [
        "Chứng minh nhân dân" => 1,
        "Số hộ chiếu" => 2,
    ],
    "accepted_paymen_type" => [
        "COM" => "COM",
        "Thưởng" => "Thưởng",
        "Thuê khoán" => "Thuê khoán",
        "Lãi vay" => "Lãi vay",
    ],
    "list_countries" => ["AFGHANISTAN" => "AF", 'ALBANIA' => 'AL', 'ALGERIA' => 'DZ', 'AMERICAN SAMOA' => 'AS', 'ANDORRA' => 'AD', 'ANGOLA' => 'AO', 'ANGUILLA' => 'AI', 'ANTARCTICA' => 'AQ', 'ANTIGUA AND BARBUDA' => 'AG', 'ARGENTINA' => 'AR', 'ARMENIA' => 'AM', 'ARUBA' => 'AW', 'AUSTRALIA' => 'AU', 'AUSTRIA' => 'AT', 'AZERBAIJAN' => 'AZ', 'BAHAMAS' => 'BS', 'BAHRAIN' => 'BH', 'BANGLADESH' => 'BD', 'BARBADOS' => 'BB', 'BELARUS' => 'BY', 'BELGIUM' => 'BE', 'BELIZE' => 'BZ', 'BENIN' => 'BJ', 'BERMUDA' => 'BM', 'BHUTAN' => 'BT', 'BOLIVIA' => 'BO', 'BOSNIA AND HERZEGOVINA' => 'BA', 'BOTSWANA' => 'BW', 'BOUVET ISLAND' => 'BV', 'BRAZIL' => 'BR', 'BRITISH INDIAN OCEAN TERRITORY' => 'IO', 'BRUNEI DARUSSALAM' => 'BN', 'BULGARIA' => 'BG', 'BURKINA FASO' => 'BF', 'BURUNDI' => 'BI', 'CAMBODIA' => 'KH', 'CAMEROON' => 'CM', 'CANADA' => 'CA', 'CAPE VERDE' => 'CV', 'CAYMAN ISLANDS' => 'KY', 'CENTRAL AFRICAN REPUBLIC' => 'CF', 'CHAD' => 'TD', 'CHILE' => 'CL', 'CHINA' => 'CN', 'CHRISTMAS ISLAND' => 'CX', 'COCOS (KEELING) ISLANDS' => 'CC', 'COLOMBIA' => 'CO', 'COMOROS' => 'KM', 'CONGO' => 'CG', 'CONGO, THE DEMOCRATIC REPUBLIC OF THE' => 'CD', 'COOK ISLANDS' => 'CK', 'COSTA RICA' => 'CR', 'COTE D IVOIRE' => 'CI', 'CROATIA' => 'HR', 'CUBA' => 'CU', 'CYPRUS' => 'CY', 'CZECH REPUBLIC' => 'CZ', 'DENMARK' => 'DK', 'DJIBOUTI' => 'DJ', 'DOMINICA' => 'DM', 'DOMINICAN REPUBLIC' => 'DO', 'EAST TIMOR' => 'TP', 'ECUADOR' => 'EC', 'EGYPT' => 'EG', 'EL SALVADOR' => 'SV', 'EQUATORIAL GUINEA' => 'GQ', 'ERITREA' => 'ER', 'ESTONIA' => 'EE', 'ETHIOPIA' => 'ET', 'FALKLAND ISLANDS (MALVINAS)' => 'FK', 'FAROE ISLANDS' => 'FO', 'FIJI' => 'FJ', 'FINLAND' => 'FI', 'FRANCE' => 'FR', 'FRENCH GUIANA' => 'GF', 'FRENCH POLYNESIA' => 'PF', 'FRENCH SOUTHERN TERRITORIES' => 'TF', 'GABON' => 'GA', 'GAMBIA' => 'GM', 'GEORGIA' => 'GE', 'GERMANY' => 'DE', 'GHANA' => 'GH', 'GIBRALTAR' => 'GI', 'GREECE' => 'GR', 'GREENLAND' => 'GL', 'GRENADA' => 'GD', 'GUADELOUPE' => 'GP', 'GUAM' => 'GU', 'GUATEMALA' => 'GT', 'GUINEA' => 'GN', 'GUINEA-BISSAU' => 'GW', 'GUYANA' => 'GY', 'HAITI' => 'HT', 'HEARD ISLAND AND MCDONALD ISLANDS' => 'HM', 'HOLY SEE (VATICAN CITY STATE)' => 'VA', 'HONDURAS' => 'HN', 'HONG KONG' => 'HK', 'HUNGARY' => 'HU', 'ICELAND' => 'IS', 'INDIA' => 'IN', 'INDONESIA' => 'ID', 'IRAN, ISLAMIC REPUBLIC OF' => 'IR', 'IRAQ' => 'IQ', 'IRELAND' => 'IE', 'ISRAEL' => 'IL', 'ITALY' => 'IT', 'JAMAICA' => 'JM', 'JAPAN' => 'JP', 'JORDAN' => 'JO', 'KAZAKSTAN' => 'KZ', 'KENYA' => 'KE', 'KIRIBATI' => 'KI', 'KOREA DEMOCRATIC PEOPLES REPUBLIC OF' => 'KP', 'KOREA REPUBLIC OF' => 'KR', 'KUWAIT' => 'KW', 'KYRGYZSTAN' => 'KG', 'LAO PEOPLES DEMOCRATIC REPUBLIC' => 'LA', 'LATVIA' => 'LV', 'LEBANON' => 'LB', 'LESOTHO' => 'LS', 'LIBERIA' => 'LR', 'LIBYAN ARAB JAMAHIRIYA' => 'LY', 'LIECHTENSTEIN' => 'LI', 'LITHUANIA' => 'LT', 'LUXEMBOURG' => 'LU', 'MACAU' => 'MO', 'MACEDONIA, THE FORMER YUGOSLAV REPUBLIC OF' => 'MK', 'MADAGASCAR' => 'MG', 'MALAWI' => 'MW', 'MALAYSIA' => 'MY', 'MALDIVES' => 'MV', 'MALI' => 'ML', 'MALTA' => 'MT', 'MARSHALL ISLANDS' => 'MH', 'MARTINIQUE' => 'MQ', 'MAURITANIA' => 'MR', 'MAURITIUS' => 'MU', 'MAYOTTE' => 'YT', 'MEXICO' => 'MX', 'MICRONESIA, FEDERATED STATES OF' => 'FM', 'MOLDOVA, REPUBLIC OF' => 'MD', 'MONACO' => 'MC', 'MONGOLIA' => 'MN', 'MONTSERRAT' => 'MS', 'MOROCCO' => 'MA', 'MOZAMBIQUE' => 'MZ', 'MYANMAR' => 'MM', 'NAMIBIA' => 'NA', 'NAURU' => 'NR', 'NEPAL' => 'NP', 'NETHERLANDS' => 'NL', 'NETHERLANDS ANTILLES' => 'AN', 'NEW CALEDONIA' => 'NC', 'NEW ZEALAND' => 'NZ', 'NICARAGUA' => 'NI', 'NIGER' => 'NE', 'NIGERIA' => 'NG', 'NIUE' => 'NU', 'NORFOLK ISLAND' => 'NF', 'NORTHERN MARIANA ISLANDS' => 'MP', 'NORWAY' => 'NO', 'OMAN' => 'OM', 'PAKISTAN' => 'PK', 'PALAU' => 'PW', 'PALESTINIAN TERRITORY, OCCUPIED' => 'PS', 'PANAMA' => 'PA', 'PAPUA NEW GUINEA' => 'PG', 'PARAGUAY' => 'PY', 'PERU' => 'PE', 'PHILIPPINES' => 'PH', 'PITCAIRN' => 'PN', 'POLAND' => 'PL', 'PORTUGAL' => 'PT', 'PUERTO RICO' => 'PR', 'QATAR' => 'QA', 'REUNION' => 'RE', 'ROMANIA' => 'RO', 'RUSSIAN FEDERATION' => 'RU', 'RWANDA' => 'RW', 'SAINT HELENA' => 'SH', 'SAINT KITTS AND NEVIS' => 'KN', 'SAINT LUCIA' => 'LC', 'SAINT PIERRE AND MIQUELON' => 'PM', 'SAINT VINCENT AND THE GRENADINES' => 'VC', 'SAMOA' => 'WS', 'SAN MARINO' => 'SM', 'SAO TOME AND PRINCIPE' => 'ST', 'SAUDI ARABIA' => 'SA', 'SENEGAL' => 'SN', 'SEYCHELLES' => 'SC', 'SIERRA LEONE' => 'SL', 'SINGAPORE' => 'SG', 'SLOVAKIA' => 'SK', 'SLOVENIA' => 'SI', 'SOLOMON ISLANDS' => 'SB', 'SOMALIA' => 'SO', 'SOUTH AFRICA' => 'ZA', 'SOUTH GEORGIA AND THE SOUTH SANDWICH ISLANDS' => 'GS', 'SPAIN' => 'ES', 'SRI LANKA' => 'LK', 'SUDAN' => 'SD', 'SURINAME' => 'SR', 'SVALBARD AND JAN MAYEN' => 'SJ', 'SWAZILAND' => 'SZ', 'SWEDEN' => 'SE', 'SWITZERLAND' => 'CH', 'SYRIAN ARAB REPUBLIC' => 'SY', 'TAIWAN, PROVINCE OF CHINA' => 'TW', 'TAJIKISTAN' => 'TJ', 'TANZANIA, UNITED REPUBLIC OF' => 'TZ', 'THAILAND' => 'TH', 'TOGO' => 'TG', 'TOKELAU' => 'TK', 'TONGA' => 'TO', 'TRINIDAD AND TOBAGO' => 'TT', 'TUNISIA' => 'TN', 'TURKEY' => 'TR', 'TURKMENISTAN' => 'TM', 'TURKS AND CAICOS ISLANDS' => 'TC', 'TUVALU' => 'TV', 'UGANDA' => 'UG', 'UKRAINE' => 'UA', 'UNITED ARAB EMIRATES' => 'AE', 'UNITED KINGDOM' => 'GB', 'UNITED STATES' => 'US', 'UNITED STATES MINOR OUTLYING ISLANDS' => 'UM', 'URUGUAY' => 'UY', 'UZBEKISTAN' => 'UZ', 'VANUATU' => 'VU', 'VENEZUELA' => 'VE', 'VIỆT NAM' => 'VN', 'VIRGIN ISLANDS, BRITISH' => 'VG', 'VIRGIN ISLANDS, U.S.' => 'VI', 'WALLIS AND FUTUNA' => 'WF', 'WESTERN SAHARA' => 'EH', 'YEMEN' => 'YE', 'YUGOSLAVIA' => 'YU', 'ZAMBIA' => 'ZM', 'ZIMBABWE' => 'ZW',],
    'mappingDataSalary' => [
        'stt' => [
            'position' => 0,
            'required' => false,
            'title' => 'STT',
            'width' => 70,
            'visible' => true,
        ],
        'employee_code' => [
            'position' => 1,
            'required' => true,
            'title' => 'MNV',
            'width' => 70,
            'visible' => true
        ],
        'cdt' => [
            'position' => 5,
            'required' => true,
            'title' => 'Chủ dự toán',
            'visible' => true,
            'width' => 240,
        ],
        'last_name' => [
            'position' => 3,
            'required' => true,
            'title' => 'Họ',
            'visible' => true,
            'width' => 140,
        ],
        'first_name' => [
            'position' => 4,
            'required' => true,
            'title' => 'Tên',
            'visible' => true,
            'width' => 120,
        ],
        'san_pham' => [
            'position' => 7,
            'required' => true,
            'title' => 'Sản phẩm',
            'visible' => true,
            'width' => 170,
        ],
        'salary_base' => [
            'position' => 15,
            'required' => false,
            'title' => 'Lương cơ bản',
            'formatter' => "money",
            'formatterParams' => ['precision' => 0],
            'visible' => false,
            'width' => 120,
        ],
        'salary_action' => [
            'position' => 17,
            'required' => false,
            'title' => 'Lương hoạt động',
            'formatter' => "money",
            'formatterParams' => ['precision' => 0],
            'visible' => true,
            'width' => 150,
        ],
        'salary_working_day' => [
            'position' => 24,
            'required' => false,
            'title' => 'Lương theo ngày công thực tế',
            'formatter' => "money",
            'formatterParams' => ['precision' => 0],
            'visible' => true,
            'width' => 175,
        ],
        'salary_working_ot_time' => [
            'position' => 28,
            'required' => false,
            'title' => 'Tổng lương làm thêm giờ',
            'formatter' => "money",
            'formatterParams' => ['precision' => 0],
            'visible' => true,
            'width' => 160,
        ],
        'salary_sub' => [
            'position' => 39,
            'required' => false,
            'title' => "Tổng phụ cấp",
            'formatter' => "money",
            'formatterParams' => ['precision' => 0],
            'visible' => false,
            'width' => 120,
        ],
        'salary_other' => [
            'position' => 47,
            'required' => false,
            'title' => 'Tổng các khoản phải thu khác',
            'formatter' => "money",
            'formatterParams' => ['precision' => 0],
            'visible' => false,
            'width' => 175,
        ],
        'total_salary_sub_other' => [
            'position' => 48,
            'required' => false,
            'title' => 'Tổng thu nhập từ lương và phụ cấp khác',
            'formatter' => "money",
            'formatterParams' => ['precision' => 0],
            'visible' => true,
            'width' => 220,
        ],
        'bao_hiem' => [
            'position' => 53,
            'required' => false,
            'title' => 'Tổng BH đóng bởi NLD',
            'formatter' => "money",
            'formatterParams' => ['precision' => 0],
            'visible' => true,
            'width' => 180,
        ],
        'giam_tru_ban_than' => [
            'position' => 67,
            'required' => false,
            'title' => 'Giảm trừ bản thân',
            'formatter' => "money",
            'formatterParams' => ['precision' => 0],
            'visible' => false,
            'width' => 140,
        ],
        'giam_tru_nguoi_phu_thuoc' => [
            'position' => 68,
            'required' => false,
            'title' => 'Giảm trừ NPT',
            'formatter' => "money",
            'formatterParams' => ['precision' => 0],
            'visible' => false,
            'width' => 140,
        ],
        'thu_nhap_khong_chiu_thue' => [
            'position' => 69,
            'required' => false,
            'title' => 'Thu nhập không chịu thuế',
            'formatter' => "money",
            'formatterParams' => ['precision' => 0],
            'visible' => false,
            'width' => 170,
        ],
        'tong_giam_tru_tinh_thue' => [
            'position' => 70,
            'required' => false,
            'title' => 'Tổng giảm trừ tính thuế',
            'formatter' => "money",
            'formatterParams' => ['precision' => 0],
            'visible' => false,
            'width' => 170,
        ],
        'thu_nhap_tinh_thue' => [
            'position' => 71,
            'required' => false,
            'title' => 'Thu nhập tính thuế',
            'formatter' => "money",
            'formatterParams' => ['precision' => 0],
            'visible' => false,
            'width' => 150,
        ],
        'tncn' => [
            'position' => 72,
            'required' => false,
            'title' => 'Thuế TNCN',
            'formatter' => "money",
            'formatterParams' => ['precision' => 0],
            'visible' => true
        ],
        'thuc_nhan' => [
            'position' => 73,
            'required' => false,
            'title' => "Thực nhận",
            'formatter' => "money",
            'formatterParams' => ['precision' => 0],
            'visible' => true
        ],
    ],
    'mappingDataFTT' => [
        'line' => [
            'position' => 0,
            'required' => true,
            'title' => 'Line',
            'width' => 70,
            'visible' => true,
        ],
        'stt' => [
            'position' => 0,
            'required' => false,
            'title' => 'STT',
            'width' => 70,
            'visible' => true,
        ],
        'emp_name' => [
            'position' => 1,
            'required' => true,
            'title' => 'Tên NV',
            'width' => 200,
            'visible' => true,
        ],
        'employee_code' => [
            'position' => 2,
            'required' => true,
            'title' => 'Mã NV',
            'width' => 90,
            'visible' => true,
        ],
        'identity_code' => [
            'position' => 3,
            'required' => true,
            'title' => 'ID',
            'width' => 115,
            'visible' => true,
        ],
        'emp_tax_code' => [
            'position' => 4,
            'required' => true,
            'title' => 'Mã số thuế',
            'width' => 120,
            'visible' => true,
        ],
        'tong_thu_nhap_truoc_thue' => [
            'position' => 5,
            'required' => true,
            'title' => 'Tổng TN trước thuế',
            'width' => 120,
            'visible' => true,
            'formatter' => "money",
            'formatterParams' => ['precision' => 0]
        ],
        'tong_non_tax' => [
            'position' => 6,
            'required' => false,
            'title' => 'Tổng Non tax',
            'width' => 120,
            'visible' => false,
            'formatter' => "money",
            'formatterParams' => ['precision' => 0],
        ],
        'tong_tnct' => [
            'position' => 7,
            'required' => true,
            'title' => 'Tổng TNCT',
            'formatter' => "money",
            'formatterParams' => ['precision' => 0],
            'visible' => true,
        ],
        'bhxh' => [
            'position' => 8,
            'required' => false,
            'title' => 'BHXH',
            'formatter' => "money",
            'formatterParams' => ['precision' => 0],
            'visible' => false,
        ],
        'thue_tam_trich' => [
            'position' => 9,
            'required' => true,
            'title' => 'Thuế tạm trích',
            'formatter' => "money",
            'formatterParams' => ['precision' => 0],
            'visible' => true,
        ],
        'thuc_nhan' => [
            'position' => 10,
            'required' => true,
            'title' => 'Thực nhận',
            'formatter' => "money",
            'formatterParams' => ['precision' => 0],
            'visible' => true,
        ],
        'giam_tru_ban_than' => [
            'position' => 11,
            'required' => false,
            'title' => 'Giảm trừ bản thân',
            'formatter' => "money",
            'formatterParams' => ['precision' => 0],
            'visible' => false,
        ],
        'giam_tru_gia_canh' => [
            'position' => 12,
            'required' => false,
            'title' => 'Giảm trừ gia cảnh',
            'formatter' => "money",
            'formatterParams' => ['precision' => 0],
            'visible' => false,
        ],
        'note' => [
            'position' => 13,
            'required' => true,
            'title' => 'Note',

            'visible' => true,
        ],
        'noi_dung' => [
            'position' => 15,
            'required' => false,
            'title' => 'Nội dung',
            'visible' => true,
        ],
        'identity_type'=>[
            'position' => 16,
            'required' => false,
            'title' => 'Loại thẻ',
            'visible' => false,
        ],
        'emp_live_status'=>[
            'position' => 17,
            'required' => false,
            'title' => 'Tình trạng cư trú',
            'visible' => false,
        ],
        'emp_country'=>[
            'position' => 18,
            'required' => false,
            'title' => 'Quốc tịch',
            'visible' => false,
        ]
    ],
    'mappingDataSalary' => [
        'line' => [
            'position' => 0,
            'required' => true,
            'title' => 'Line',
            'width' => 70,
            'visible' => true,
        ],
        'stt' => [
            'position' => 0,
            'required' => false,
            'title' => 'STT',
            'width' => 70,
            'visible' => true,
        ],
        'emp_name' => [
            'position' => "Tên NV",
            'required' => true,
            'title' => 'Tên NV',
            'width' => 200,
            'visible' => true,
        ],
        'employee_code' => [
            'position' => "Mã NV",
            'required' => true,
            'title' => 'Mã NV',
            'width' => 90,
            'visible' => true,
        ],
        'tong_thu_nhap_truoc_thue' => [
            'position' => "Tổng TN trước thuế",
            'required' => true,
            'title' => 'Tổng TN trước thuế',
            'width' => 120,
            'visible' => true,
            'formatter' => "money",
            'formatterParams' => ['precision' => 0]
        ],
        'tong_non_tax' => [
            'position' => "Tổng Non tax",
            'required' => false,
            'title' => 'Tổng Non tax',
            'width' => 120,
            'visible' => false,
            'formatter' => "money",
            'formatterParams' => ['precision' => 0],
        ],
        'tong_tnct' => [
            'position' => 7,
            'required' => true,
            'title' => 'Tổng TNCT',
            'formatter' => "money",
            'formatterParams' => ['precision' => 0],
            'visible' => true,
        ],
        'bhxh' => [
            'position' => 8,
            'required' => false,
            'title' => 'BHXH',
            'formatter' => "money",
            'formatterParams' => ['precision' => 0],
            'visible' => false,
        ],
        'thue_tam_trich' => [
            'position' => "Thuế tạm trích",
            'required' => true,
            'title' => 'Thuế tạm trích',
            'formatter' => "money",
            'formatterParams' => ['precision' => 0],
            'visible' => true,
        ],
        'thuc_nhan' => [
            'position' => "Thực nhận",
            'required' => true,
            'title' => 'Thực nhận',
            'formatter' => "money",
            'formatterParams' => ['precision' => 0],
            'visible' => true,
        ],
        'giam_tru_ban_than' => [
            'position' => 11,
            'required' => false,
            'title' => 'Giảm trừ bản thân',
            'formatter' => "money",
            'formatterParams' => ['precision' => 0],
            'visible' => false,
        ],
        'giam_tru_gia_canh' => [
            'position' => 12,
            'required' => false,
            'title' => 'Giảm trừ gia cảnh',
            'formatter' => "money",
            'formatterParams' => ['precision' => 0],
            'visible' => false,
        ],
        'note' => [
            'position' => 13,
            'required' => true,
            'title' => 'Note',

            'visible' => true,
        ],
        'noi_dung' => [
            'position' => 15,
            'required' => false,
            'title' => 'Nội dung',
            'visible' => true,
        ],
        'identity_type'=>[
            'position' => 16,
            'required' => false,
            'title' => 'Loại thẻ',
            'visible' => false,
        ],
        'emp_live_status'=>[
            'position' => 17,
            'required' => false,
            'title' => 'Tình trạng cư trú',
            'visible' => false,
        ],
        'emp_country'=>[
            'position' => 18,
            'required' => false,
            'title' => 'Quốc tịch',
            'visible' => false,
        ]
    ],
    'accepted_currency' => [
        'ALL' => 'Albania Lek',
        'AFN' => 'Afghanistan Afghani',
        'ARS' => 'Argentina Peso',
        'AWG' => 'Aruba Guilder',
        'AUD' => 'Australia Dollar',
        'AZN' => 'Azerbaijan New Manat',
        'BSD' => 'Bahamas Dollar',
        'BBD' => 'Barbados Dollar',
        'BDT' => 'Bangladeshi taka',
        'BYR' => 'Belarus Ruble',
        'BZD' => 'Belize Dollar',
        'BMD' => 'Bermuda Dollar',
        'BOB' => 'Bolivia Boliviano',
        'BAM' => 'Bosnia and Herzegovina Convertible Marka',
        'BWP' => 'Botswana Pula',
        'BGN' => 'Bulgaria Lev',
        'BRL' => 'Brazil Real',
        'BND' => 'Brunei Darussalam Dollar',
        'KHR' => 'Cambodia Riel',
        'CAD' => 'Canada Dollar',
        'KYD' => 'Cayman Islands Dollar',
        'CLP' => 'Chile Peso',
        'CNY' => 'China Yuan Renminbi',
        'COP' => 'Colombia Peso',
        'CRC' => 'Costa Rica Colon',
        'HRK' => 'Croatia Kuna',
        'CUP' => 'Cuba Peso',
        'CZK' => 'Czech Republic Koruna',
        'DKK' => 'Denmark Krone',
        'DOP' => 'Dominican Republic Peso',
        'XCD' => 'East Caribbean Dollar',
        'EGP' => 'Egypt Pound',
        'SVC' => 'El Salvador Colon',
        'EEK' => 'Estonia Kroon',
        'EUR' => 'Euro Member Countries',
        'FKP' => 'Falkland Islands (Malvinas) Pound',
        'FJD' => 'Fiji Dollar',
        'GHC' => 'Ghana Cedis',
        'GIP' => 'Gibraltar Pound',
        'GTQ' => 'Guatemala Quetzal',
        'GGP' => 'Guernsey Pound',
        'GYD' => 'Guyana Dollar',
        'HNL' => 'Honduras Lempira',
        'HKD' => 'Hong Kong Dollar',
        'HUF' => 'Hungary Forint',
        'ISK' => 'Iceland Krona',
        'INR' => 'India Rupee',
        'IDR' => 'Indonesia Rupiah',
        'IRR' => 'Iran Rial',
        'IMP' => 'Isle of Man Pound',
        'ILS' => 'Israel Shekel',
        'JMD' => 'Jamaica Dollar',
        'JPY' => 'Japan Yen',
        'JEP' => 'Jersey Pound',
        'KZT' => 'Kazakhstan Tenge',
        'KPW' => 'Korea (North) Won',
        'KRW' => 'Korea (South) Won',
        'KGS' => 'Kyrgyzstan Som',
        'LAK' => 'Laos Kip',
        'LVL' => 'Latvia Lat',
        'LBP' => 'Lebanon Pound',
        'LRD' => 'Liberia Dollar',
        'LTL' => 'Lithuania Litas',
        'MKD' => 'Macedonia Denar',
        'MYR' => 'Malaysia Ringgit',
        'MUR' => 'Mauritius Rupee',
        'MXN' => 'Mexico Peso',
        'MNT' => 'Mongolia Tughrik',
        'MZN' => 'Mozambique Metical',
        'NAD' => 'Namibia Dollar',
        'NPR' => 'Nepal Rupee',
        'ANG' => 'Netherlands Antilles Guilder',
        'NZD' => 'New Zealand Dollar',
        'NIO' => 'Nicaragua Cordoba',
        'NGN' => 'Nigeria Naira',
        'NOK' => 'Norway Krone',
        'OMR' => 'Oman Rial',
        'PKR' => 'Pakistan Rupee',
        'PAB' => 'Panama Balboa',
        'PYG' => 'Paraguay Guarani',
        'PEN' => 'Peru Nuevo Sol',
        'PHP' => 'Philippines Peso',
        'PLN' => 'Poland Zloty',
        'QAR' => 'Qatar Riyal',
        'RON' => 'Romania New Leu',
        'RUB' => 'Russia Ruble',
        'SHP' => 'Saint Helena Pound',
        'SAR' => 'Saudi Arabia Riyal',
        'RSD' => 'Serbia Dinar',
        'SCR' => 'Seychelles Rupee',
        'SGD' => 'Singapore Dollar',
        'SBD' => 'Solomon Islands Dollar',
        'SOS' => 'Somalia Shilling',
        'ZAR' => 'South Africa Rand',
        'LKR' => 'Sri Lanka Rupee',
        'SEK' => 'Sweden Krona',
        'CHF' => 'Switzerland Franc',
        'SRD' => 'Suriname Dollar',
        'SYP' => 'Syria Pound',
        'TWD' => 'Taiwan New Dollar',
        'THB' => 'Thailand Baht',
        'TTD' => 'Trinidad and Tobago Dollar',
        'TRY' => 'Turkey Lira',
        'TRL' => 'Turkey Lira',
        'TVD' => 'Tuvalu Dollar',
        'UAH' => 'Ukraine Hryvna',
        'GBP' => 'United Kingdom Pound',
        'USD' => 'United States Dollar',
        'UYU' => 'Uruguay Peso',
        'UZS' => 'Uzbekistan Som',
        'VEF' => 'Venezuela Bolivar',
        'VND' => 'Viet Nam Dong',
        'YER' => 'Yemen Rial',
        'ZWD' => 'Zimbabwe Dollar'
    ],
    'allow_order_filters' => [
        'id',
        'ma_osscar',
        'san_pham',
        'ma_du_toan',
        'serial',
        'phong_ban',
        'phap_nhan',
        'ngay_de_xuat',
        'nguoi_de_xuat',
        'noi_dung',
        'nguoi_huong',
        'so_tien',
        'loai_tien',
        'ty_gia',
        'quy_doi',
        'month',
        'status',
        'ngay_thanh_toan',
        'isSalary',
        'month',
        'year'],
    'list_note_import_ftt' => [
        'rent' => ['TKCM'],
        'com' => ['Com NV', 'Com CTV'],
        'bonus' => ['Thưởng NV', 'Thưởng CTV'],
        'interest' => ['Lãi vay']
    ],
    'mappingDataCrossCheck' => [
        'serial_xbeat' => [
            'position' => 'so_serial'
        ],
        'serial' => [
            'type' => 'pattern',
            'sourceCollumn' => 'dien_giai',
            'pattern' => "/^\d+/",
        ],
        'ngay_chung_tu' => [
            'position' => 'ngay_c.tu'
        ],
        'ma_chung_tu' => [
            'position' => 'ma_c.tu_in'
        ],
        'so_chung_tu' => [
            'position' => 'so_c.tu'
        ],
        'ma_khach' => [
            'position' => 'ma_khach'
        ],
        'ten_khach' => [
            'position' => 'ten_khach_hang'
        ],
        'dien_giai' => [
            'position' => 'dien_giai'
        ],
        'tai_khoan' => [
            'position' => 'tk'
        ],
        'tai_khoan_doi_ung' => [
            'position' => 'tk_d.ung'
        ],
        'ps_no' => [
            'position' => 'ps_no'
        ],
        'ps_co' => [
            'position' => 'ps_co'
        ],
        'ma_du_an' => [
            'position' => 'ma_du_an'
        ],
        'ma_chung_tu_0' => [
            'position' => 'ma_c.tu_0'
        ]
    ],
    'hr20' => [
        "url" => [
            "getFullData" => "http://hrdata.topica.vn:8282/api/v1.0/hrdata",
            "getToken" => "http://hrdata.topica.vn:8282/api/oauth/token-consumer",
        ],
        "params" => [
            "getToken" => [
                "Email" => "sf18.quantrithunhap@topica.edu.vn",
                "Password" => "d5ec92e6-4b9f-4b81-9d69-1a07daf08b71"
            ]
        ]
    ],
];